#pragma once
enum EventType {
	EVENT_COLLISION,
	NUM_TYPES
};

enum ComponentID {
	TRANSFORM_COMPONENT,
	DRAW_COMPONENT,
	COLLISION_COMPONENT,
	USER_INPUT_COMPONENT,
	PHYSICS_COMPONENT,
	PLAYER_COMPONENT,
	NUM_COMPONENTS,
};
